[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open", orphan = true },
]
zathura = [
	{ run = 'zathura "$@"', desc = "Open with zathura", orphan = true }
]
loupe = [
	{ run = 'loupe "$@"', desc = "Open with Loupe", orphan = true }
]
wine = [
	{ run = 'wine "$@"', desc = "Run Windows programs", orphan = true }
]
bat = [
	{ run = 'bat "$@"', desc = "Open with bat", block = true }
]
mpv = [
	{ run = 'mpv "$@"', desc = "Play with mpv", block = true }
]

[open]
prepend_rules = [
	{ name = "*.pdf", use = [ "zathura", "open" ]},
	{ name = "*.exe", use = "wine" },
	# Multiple openers for a single rule
	{ name = "*.html", use = [ "open", "edit" ] },
]

append_rules = [
	{ name = "*", use = [ "edit", "bat", "open" ]},
]

rules = [
	{ mime = "image/*", use = "loupe" },
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "mpv" },
    { mime = "audio/*", use = "mpv" },
    { mime = "application/pdf", use = "zathura" }
]
